server.port=8084

# Databasanslutning
spring.datasource.url=jdbc:mysql://journal-mysql:3306/journaldb
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Keycloak-konfiguration
# Här använder vi den interna Docker-adressen
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://keycloak:8080/realms/journal
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://keycloak:8080/realms/journal/protocol/openid-connect/certs

# Actuator
management.endpoints.web.exposure.include=health
management.endpoint.health.probes.enabled=true