#################################
# Server
#################################
quarkus.http.port=${PORT:8080}
quarkus.http.host=0.0.0.0
quarkus.http.root-path=/search-services

#################################
# CORS
#################################
quarkus.http.cors=true
quarkus.http.cors.origins=*
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=accept,content-type,origin,authorization,x-requested-with

#################################
# REST Client (Journal Service)
#################################
quarkus.rest-client.journal-client.url=http://journal-service:8084
quarkus.rest-client.logging.scope=request-response
quarkus.rest-client.logging.body-limit=100000

#################################
# Keycloak / OIDC
#################################
quarkus.oidc.auth-server-url=http://keycloak:8080/realms/journal
quarkus.oidc.client-id=search-service
quarkus.oidc.credentials.secret=CHANGE_ME
quarkus.oidc.application-type=service

#################################
# Security
#################################
quarkus.http.auth.permission.authenticated.paths=/*
quarkus.http.auth.permission.authenticated.policy=authenticated
