# --- BUILD ---
FROM quay.io/quarkus/ubi-quarkus-mandrel-builder-image:23.1-java21 AS build

WORKDIR /workspace

COPY mvnw mvnw
COPY .mvn .mvn
COPY pom.xml .
COPY src src

RUN chmod +x mvnw || true
RUN ./mvnw -q -DskipTests package

# --- RUN ---
FROM eclipse-temurin:21-jre

WORKDIR /app
COPY --from=build /workspace/target/quarkus-app/ ./

EXPOSE 8082
CMD ["java", "-jar", "quarkus-run.jar"]
